apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dynamic-gateway-service.fullname" . }}-static-start-scripts
data:
  gateway-peering.js: |
{{ .Files.Get "static/gateway-peering.js" | indent 4 }}
  syslog-tcp.js: |
{{ .Files.Get "static/syslog-tcp.js" | indent 4 }}
  dp-requirement-error.sh: |
{{ .Files.Get "static/dp-requirement-error.sh" | indent 4 -}}
