{{- if and .Values.datapowerMonitor.image.repository .Values.datapowerMonitor.image.tag -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dpm-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-dpm-pod-reader-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-dpm-pod-reader-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-dpm-pod-reader-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-dpm-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datapower-monitor
  labels:
    app: datapower-monitor
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapower-monitor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: datapower-monitor
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.datapower.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.datapower.image.pullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-dpm-sa
      containers:
      - name: datapower-monitor
        image: "{{ .Values.datapowerMonitor.image.repository }}:{{ .Values.datapowerMonitor.image.tag }}"
        env:
          - name: POD_LABEL_SELECTOR
            value: "app=={{ template "dynamic-gateway-service.name" . }},release=={{ .Release.Name }}"
        resources:
          requests:
            cpu: "1"
            memory: 256Mi
          limits:
            cpu: "2"
            memory: "2Gi"
{{- if .Values.datapower.adminUserSecret }}
        volumeMounts:
          - name: admin-user-password
            mountPath: /usr/share/admin-password
      volumes:
        - name: admin-user-password
          secret:
            secretName: {{ .Values.datapower.adminUserSecret }}
{{- end }}
{{- end -}}
