---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dpm-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-dpm-pod-reader-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-dpm-pod-reader-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-dpm-pod-reader-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-dpm-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dpm-svc
  labels:
    app: datapower-monitor
spec:
  ports:
  - port: {{ .Values.datapowerMonitor.livenessPort | default 8080 }}
    targetPort: {{ .Values.datapowerMonitor.livenessPort | default 8080 }}
    protocol: TCP
    name: dpm-liveness
  selector:
    app: datapower-monitor
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datapower-monitor
  labels:
    app: datapower-monitor
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapower-monitor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: datapower-monitor
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.datapower.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.datapower.image.pullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-dpm-sa
      containers:
      - name: datapower-monitor
        image: "{{ .Values.datapowerMonitor.image.repository }}:{{ .Values.datapowerMonitor.image.tag }}"
        env:
          - name: POD_LABEL_SELECTOR
            value: "app=={{ template "dynamic-gateway-service.name" . }},release=={{ .Release.Name }}"
          - name: DP_XML_MGMT_PORT
            value: {{ .Values.datapower.xmlManagementLocalPort | quote }}
          - name: LIVENESS_CHECK_SERVER_ENABLED
            value: "true"
          - name: LIVENESS_CHECK_SERVER_PORT
            value: {{ .Values.datapowerMonitor.livenessPort | default 8080 | quote }}
          - name: POD_LIFECYCLE_EVENT_DEBOUNCE_MS
            value: {{ .Values.datapowerMonitor.env.lifecycleDebounceMs | default 10000 | quote }}
          - name: PEERING_RECOVERY_CHECK_INTERVAL_MS
            value: {{ .Values.datapowerMonitor.env.peeringRecoveryCheckIntervalMs | default 1000 | quote }}
        ports:
          - containerPort: {{ .Values.datapowerMonitor.livenessPort | default 8080 }}
            name: dpm-liveness
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: dpm-liveness
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        resources:
{{ toYaml .Values.datapowerMonitor.resources | indent 10 }}
{{- if .Values.datapower.adminUserSecret }}
        volumeMounts:
          - name: admin-user-password
            mountPath: /usr/share/admin-password
      volumes:
        - name: admin-user-password
          secret:
            secretName: {{ .Values.datapower.adminUserSecret }}
{{- end }}
