apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "dynamic-gateway-service.fullname" . }}
  labels:
    app: {{ template "dynamic-gateway-service.name" . }}
    chart: {{ template "dynamic-gateway-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "dynamic-gateway-service.fullname" . }}
  replicas: {{ .Values.datapower.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "dynamic-gateway-service.name" . }}
      release: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        webGUIPort: {{ .Values.datapower.webGuiManagementPort | quote }}
        sshPort: {{ .Values.datapower.gatewaySshPort | quote }}
        restPort: {{ .Values.datapower.restManagementPort | quote }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/snmp'
        prometheus.io/port: '63512'
        prometheus.io/target: '127.0.0.1:{{ .Values.datapower.snmpPort }}'
        prometheus.io/module: 'dpStatusMIB'
{{- $licenseVersion := quote .Values.datapower.licenseVersion -}}
{{- if .Values.cip }}
  {{- if eq (include "datapower-requirements.validLicenseVersion" .) "true" }}
        productVersion: "{{ .Values.datapower.image.tag }}"
    {{- if eq $licenseVersion ("Production" | quote) }}
        productID: 'DPGateway_5737_I89_ICIP_chargeable'
        productName: 'IBM Cloud Integration Platform - DataPower Gateway (Chargeable)'
    {{- else if eq $licenseVersion ("Nonproduction" | quote) }}
        productID: 'DPGateway_5737_I89_ICIP_nonProd_chargeable'
        productName: 'IBM Cloud Integration Platform (non-production) - DataPower Gateway (Chargeable)'
    {{- else }}
        productID: 'IBMDataPowerGatewayVirtualEdition_{{ .image.tag }}_Developers'
    {{- end }}
  {{- end }}
{{- else }}
  {{- if eq (include "datapower-requirements.validLicenseVersion" .) "true" }}
        productFlexpointBundle: "{{ .Values.datapower.flexpointBundle }}"
        productMetric: "PROCESSOR_VALUE_UNIT"
        productVersion: "{{ .Values.datapower.image.tag }}"
    {{- if eq $licenseVersion ("Production" | quote) }}
        productID: '887a7b80dd7b40c9b978ff085230604e'
        productChargedContainers: "all"
    {{- else if eq $licenseVersion ("Nonproduction" | quote) }}
        productID: 'bd624448e8484592879f2e1a950686bd'
        productChargedContainers: "all"
    {{- else }}
        productID: 'IBMDataPowerGatewayVirtualEdition_{{ .Values.datapower.image.tag }}_Developers'
        productChargedContainers: ""
    {{- end }}
  {{- end }}
{{- end }}
      labels:
        app: {{ template "dynamic-gateway-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.datapower.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.datapower.image.pullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
{{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: {{ template "dynamic-gateway-service.name" . }}
                  release: {{ .Release.Name }}
{{- end }}
{{/* Define the initContainer only if the requirements are satisfied */}}
{{- if eq (include "datapower-requirements.satisfied" .) "true"}}
      initContainers:
        - name: dpinit
          image: "{{ .Values.datapower.busybox.repository }}:{{ .Values.datapower.busybox.tag }}"
          imagePullPolicy: {{ .Values.datapower.busybox.pullPolicy }} 
          env:
            - name: DPM_FQDN
              value: "{{ .Release.Name }}-dpm-svc.{{ .Release.Namespace }}.svc.cluster.local"
            - name: DPM_LIVENESS_PORT
              value: {{ .Values.datapowerMonitor.livenessPort | default 8080 | quote }}
          command:
            - sh
            - -c
            - |
              sh /init/scripts/init-dpm-check.sh
              cp -RL /init/config/* /drouter/config
{{- if .Values.datapower.adminUserSecret }}
              sh /init/scripts/init-admin-user.sh
{{- end }}
{{- if .Values.datapower.customDatapowerConfig }}
              cat /init/custom-config/*.cfg > /drouter/config/apiconnect/custom-config.cfg
{{- end }}
{{/* If SSH is enabled, DP runs as root. Only chown if SSH is not enabled */}}
{{- if ne .Values.datapower.gatewaySshState "enabled" }}
              chown -R 101:101 /drouter/config /root/secure/usrcerts/apiconnect
{{- end }}
              chmod -R 0777 /drouter/config /root/secure/usrcerts/apiconnect
{{- if eq (.Values.datapower.env.enableTMS | default "off") "on" }}
{{/* If SSH is enabled, DP runs as root. Only chown if SSH is not enabled */}}
{{- if ne .Values.datapower.gatewaySshState "enabled" }}
              find /drouter/ramdisk2/mnt -type d -exec chown 101:101 {} \;
{{- end }}
              find /drouter/ramdisk2/mnt -type d -exec chmod 0777 {} \;
{{- end }}
          volumeMounts:
            - name: init-config-volume
              mountPath: /init/config
            - name: init-config-apiconnect-volume
              mountPath: /init/config/apiconnect
            - name: init-scripts-volume
              mountPath: /init/scripts
            - name: drouter-config-volume
              mountPath: /drouter/config
            - name: root-secure-usrcerts-apiconnect-volume
              mountPath: /root/secure/usrcerts/apiconnect
            - name: drouter-ramdisk2-volume
              mountPath: /drouter/ramdisk2
{{- if eq (.Values.datapower.env.enableTMS | default "off") "on" }}
            - name: tms
              mountPath: /drouter/ramdisk2/mnt/raid-volume/raid0/local
{{- end }}
{{- if .Values.datapower.adminUserSecret }}
            - name: init-admin-user-secret
              mountPath: /init/admin-user-secret
{{- end }}
{{- if .Values.datapower.customDatapowerConfig }}
            - name: init-custom-config-volume
              mountPath: /init/custom-config
{{- end }}
{{- else }}
{{/* No initContainer if requirements are not satisfied */}}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.datapower.image.repository }}:{{ .Values.datapower.image.tag }}"
          imagePullPolicy: {{ .Values.datapower.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
# Dynamically increase the user permissions of the DataPower container when SSH is enabled.
{{- if eq .Values.datapower.gatewaySshState "enabled" }}
            runAsNonRoot: false
            runAsUser: 0
{{- else }}
            runAsNonRoot: true
            runAsUser: 101
{{- end }}
            capabilities:
              drop:
              - ALL
# Add capabilities needed for SSH only when SSH is enabled
{{- if eq .Values.datapower.gatewaySshState "enabled" }}
              add:
              - SETGID
              - SETUID
              - SYS_CHROOT
              - DAC_OVERRIDE
{{- end }}
          command:
            - sh
            - -c
            - |
{{- if eq (include "datapower-requirements.satisfied" .) "true"}}
              set -x
              export $(env | grep ^DATAPOWER_ | cut -d= -f1)
              /root/node /start/gateway-peering.js
              exec /start.sh --log-format {{ .Values.datapower.env.defaultLogFormat }}
{{- else }}
              sh /start/dp-requirement-error.sh
              exit 1
{{- end }}
          stdin: true
          tty: true
          env:
{{- if eq (include "datapower-requirements.satisfied" .) "false"}}
            - name: DP_REQ_VALID_LICENSE_VERSION
              value: "{{ template "datapower-requirements.validLicenseVersion" . }}"
            - name: DP_REQ_VALID_DPM_IMAGE_SET
              value: "{{ template "datapower-requirements.dpmImageSet" . }}"
            - name: DP_REQ_HP_PEERING_OPTION_SET
              value: "{{ template "datapower-requirements.hpPeeringOptionSet" . }}"
{{- end }}
            - name: APICONNECT_K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: APICONNECT_K8S_PEERS_SVC_NAME
              value: {{ template "dynamic-gateway-service.fullname" . }}
            - name: APICONNECT_V5_COMPAT_MODE
{{/* Enforce valid values for apicGatewayServiceV5CompatibilityMode as 'on' and 'off' (default: 'on') */}}
{{- if .Values.datapower.apicGatewayServiceV5CompatibilityMode }}
{{- if eq .Values.datapower.apicGatewayServiceV5CompatibilityMode "off" }}
              value: "off"
{{- else }}
              value: "on"
{{- end }}
{{- else }}
              value: "on"
{{- end }}
            - name: APICONNECT_ENABLE_TMS
{{/* Enforce valid values for enableTMS as 'on' and 'off' (default: 'off') */}}
{{- if eq (.Values.datapower.env.enableTMS | default "off") "on" }}
              value: "on"
{{- else }}
              value: "off"
{{- end }}
            - name: APICONNECT_API_DEBUG_PROBE
{{/* Enforce valid values for apiDebugProbe as 'enabled' and 'disabled' (default: 'disabled') */}}
{{- if eq (.Values.datapower.apiDebugProbe | default "disabled") "enabled" }}
              value: "enabled"
{{- else }}
              value: "disabled"
{{- end }}
{{- if and (eq (.Values.datapower.apicGatewayServiceV5CompatibilityMode | default "on") "off") (eq (.Values.datapower.env.highPerformancePeering | default "") "on") }}
            - name: APICONNECT_DEDICATED_RL_PEERING
              value: "on"
            - name: APICONNECT_DEDICATED_SUBS_PEERING
              value: "on"
{{- else }}
            - name: APICONNECT_DEDICATED_RL_PEERING
              value: "off"
            - name: APICONNECT_DEDICATED_SUBS_PEERING
              value: "off"
{{- end }}
            - name: GATEWAY_PEERING_MONITOR_PORT
              value: {{ .Values.datapower.gatewayPeeringMonitorPort | quote }}
            - name: GATEWAY_PEERING_LOCAL_PORT
              value: {{ .Values.datapower.gatewayPeeringLocalPort | quote }}
            - name: GATEWAY_PEERING_ENABLE_SSL
              value: {{ .Values.datapower.env.peeringEnableSSL | quote }}
            - name: TMS_PEERING_MONITOR_PORT
              value: {{ .Values.datapower.tmsPeeringMonitorPort | quote }}
            - name: TMS_PEERING_LOCAL_PORT
              value: {{ .Values.datapower.tmsPeeringLocalPort | quote }}
            - name: TMS_PEERING_ENABLE_SSL
              value: {{ .Values.datapower.env.tmsPeeringEnableSSL | quote }}
            - name: ADP_PEERING_MONITOR_PORT
              value: {{ .Values.datapower.apiDebugProbePeeringMonitorPort | quote }}
            - name: ADP_PEERING_LOCAL_PORT
              value: {{ .Values.datapower.apiDebugProbePeeringLocalPort | quote }}
            - name: ADP_PEERING_ENABLE_SSL
              value: {{ .Values.datapower.env.apiDebugProbePeeringEnableSSL | quote }}
            - name: RL_PEERING_MONITOR_PORT
              value: {{ .Values.datapower.rlPeeringMonitorPort | quote }}
            - name: RL_PEERING_LOCAL_PORT
              value: {{ .Values.datapower.rlPeeringLocalPort | quote }}
            - name: RL_PEERING_ENABLE_SSL
              value: {{ .Values.datapower.env.peeringEnableSSL | quote }}
            - name: SUBS_PEERING_MONITOR_PORT
              value: {{ .Values.datapower.subsPeeringMonitorPort | quote }}
            - name: SUBS_PEERING_LOCAL_PORT
              value: {{ .Values.datapower.subsPeeringLocalPort | quote }}
            - name: SUBS_PEERING_ENABLE_SSL
              value: {{ .Values.datapower.env.peeringEnableSSL | quote }}
{{- if .Values.datapower.env.workerThreads }}
{{- if gt .Values.datapower.env.workerThreads 0.0 }}
            - name: DATAPOWER_WORKER_THREADS
              value: {{ .Values.datapower.env.workerThreads | quote }}
{{- end }}
{{- end }}
            - name: "DATAPOWER_ACCEPT_LICENSE"
              value: "true"
            - name: "DATAPOWER_LOG_COLOR"
              value: "false"
            - name: "DATAPOWER_INTERACTIVE"
              value: {{ .Values.datapower.env.interactive | quote }}
            - name: "DATAPOWER_LOG_LEVEL"
              value: {{ .Values.datapower.env.datapowerLogLevel | quote }}
            - name: "PEERING_LOG_LEVEL"
              value: {{ .Values.datapower.env.peeringLogLevel }}
            - name: "GWD_POLICY_DISABLE_LOG"
{{- if eq .Values.datapower.env.policyDisableLog "true" }}
              value: "true"
{{- else }}
              value: "false"
{{- end }}
            - name: "GWD_POLICY_DISABLE_XSLT"
{{- if eq .Values.datapower.env.policyDisableXSLT "true" }}
              value: "true"
{{- else }}
              value: "false"
{{- end }}
            - name: "GWD_POLICY_DISABLE_GATEWAYSCRIPT"
{{- if eq .Values.datapower.env.policyDisableGatewayScript "true" }}
              value: "true"
{{- else }}
              value: "false"
{{- end }}
            - name: "GWD_POLICY_DISABLE_RATELIMIT"
{{- if eq .Values.datapower.env.policyDisableRateLimit "true" }}
              value: "true"
{{- else }}
              value: "false"
{{- end }}
          resources:
{{ toYaml .Values.datapower.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.datapower.gatewayPeeringLocalPort }}
              name: peer-local-port
            - containerPort: {{ .Values.datapower.gatewayPeeringMonitorPort }}
              name: peer-monit-port
            - containerPort: {{ .Values.datapower.rlPeeringLocalPort }}
              name: rl-local-port
            - containerPort: {{ .Values.datapower.rlPeeringMonitorPort }}
              name: rl-monit-port
            - containerPort: {{ .Values.datapower.subsPeeringLocalPort }}
              name: subs-local-port
            - containerPort: {{ .Values.datapower.subsPeeringMonitorPort }}
              name: subs-monit-port
            - containerPort: {{ .Values.datapower.tmsPeeringLocalPort }}
              name: tms-local-port
            - containerPort: {{ .Values.datapower.tmsPeeringMonitorPort }}
              name: tms-monit-port
            - containerPort: {{ .Values.datapower.apiDebugProbePeeringLocalPort }}
              name: adp-local-port
            - containerPort: {{ .Values.datapower.apiDebugProbePeeringMonitorPort }}
              name: adp-monit-port
            - containerPort: {{ .Values.datapower.apicGatewayServiceLocalPort }}
              name: apic-gw-mgmt
            - containerPort: {{ .Values.datapower.apiGatewayLocalPort }}
              name: api-gw-svc
            - containerPort: {{ .Values.datapower.gatewaySshPort }}
              name: ssh-port
            - containerPort: {{ .Values.datapower.webGuiManagementPort }}
              name: webgui-port
            - containerPort: {{ .Values.datapower.restManagementPort }}
              name: rmi-port
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: apic-gw-mgmt
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /ready
              port: apic-gw-mgmt
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: start-volume
              mountPath: /start
            - name: drouter-config-volume
              mountPath: /drouter/config
            - name: root-secure-usrcerts-apiconnect-volume
              mountPath: /root/secure/usrcerts/apiconnect
            - name: root-secure-usrcerts-apiconnect-gwd-volume
              mountPath: /root/secure/usrcerts/apiconnect/gwd
            - name: drouter-ramdisk2-volume
              mountPath: /drouter/ramdisk2
            - name: drouter-temporary-volume
              mountPath: /drouter/temporary
{{- if eq (.Values.datapower.env.enableTMS | default "off") "on" }}
            - name: tms
              mountPath: /drouter/ramdisk2/mnt/raid-volume/raid0/local
{{- end }}
      volumes:
        - name: init-config-volume
          configMap:
            name: {{ template "dynamic-gateway-service.fullname" . }}-init-config
        - name: init-config-apiconnect-volume
          configMap:
            name: {{ template "dynamic-gateway-service.fullname" . }}-init-config-apic
        - name: init-scripts-volume
          configMap:
            name: {{ template "dynamic-gateway-service.fullname" . }}-static-init-scripts
{{- if .Values.datapower.adminUserSecret }}
        - name: init-admin-user-secret
          secret:
            secretName: {{ .Values.datapower.adminUserSecret }}
{{- end }}
{{- if .Values.datapower.customDatapowerConfig }}
        - name: init-custom-config-volume
          configMap:
            name: {{ .Values.datapower.customDatapowerConfig }}
{{- end }}
        - name: start-volume
          configMap:
            name: {{ template "dynamic-gateway-service.fullname" . }}-static-start-scripts
        - name: drouter-config-volume
          emptyDir: {}
        - name: root-secure-usrcerts-apiconnect-volume
          emptyDir: {}
        - name: drouter-ramdisk2-volume
          emptyDir:
            medium: ""
        - name: drouter-temporary-volume
          emptyDir:
            medium: ""
        - name: root-secure-usrcerts-apiconnect-gwd-volume
          secret:
            secretName: {{ .Values.datapower.apicGatewayServiceTLSSecret }}
{{- if eq (.Values.datapower.env.enableTMS | default "off") "on" }}
  volumeClaimTemplates:
  - metadata:
      name: tms
      labels:
        app: {{ template "dynamic-gateway-service.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{ toYaml .Values.datapower.storage.tmsPeering | indent 6 }}
{{- end }}
